INSERT INTO jqgrid_table_view (id, table_identifier, joining_query, display_header, default_filter_json, default_order_by) VALUES 
('5', 
'ScreenerPage_AdvancedAnalysisTable', 
'from nse_eq_eod_data prevDay, nse_eq_eod_data curDay, nse_eq_eod_data afterFiveDay, scrips scr
where prevDay.f_scrip = scr.id and curDay.f_scrip = scr.id and afterFiveDay.f_scrip = scr.id
and scr.symbol_type=''EQ''
and prevDay.data_date = (select max(data_date) from nse_eq_eod_data where data_date<curDay.data_date)
and afterFiveDay.data_date = (select min(data_date) from nse_eq_eod_data where data_date>=(
	(curDay.data_date) + INTERVAL ''7 days'')
)', 
'Advanced Technical Analysis', 
' and curDay.data_date = ''2015-03-02''',
'(afterFiveDay.close_price-curDay.close_price)*100/NULLIF(curDay.close_price,0) desc'
);

INSERT INTO jqgrid_table_columns (id, f_jqgrid_table, display_name, view_to_db_identifier, actual_column_name, column_type, column_fetch_order, data_formatter, is_visible, select_query, ui_width, search_where_clause, is_searchable) VALUES 
('60', '5', 'ID', 'ID', 'scr.id', 'Index', '0', 'scr.id', 'f', NULL, '100', NULL, 'f'),
('61', '5', 'Scrip', 'ScripName', 'scr.name', 'String', '5', 'scr.name', 't', NULL, '100', NULL, 't'),
('62', '5', 'PrevDayDate', 'PrevDayDate', 'prevDay.data_date as prevDate', 'Date', '10', 'prevDay.data_date as prevDate', 't', NULL, '100', NULL, 't'),
('63', '5', 'CurrentDayDate', 'CurrentDayDate', 'curDay.data_date as curDate', 'Date', '15', 'curDay.data_date as curDate', 't', NULL, '100', NULL, 't'),
('64', '5', 'AfterFiveDayDate', 'AfterFiveDayDate', 'afterFiveDay.data_date as afterFiveDate', 'Date', '20', 'afterFiveDay.data_date as afterFiveDate', 't', NULL, '100', NULL, 't'),
('65', '5', 'PrevDayClose', 'PrevDayClose', 'prevDay.close_price as prevDayClose', 'Number', '25', 'prevDay.close_price as prevDayClose', 't', NULL, '100', NULL, 't'),
('66', '5', 'CurrentDayClose', 'CurrentDayClose', 'curDay.close_price as curDayClose', 'Number', '30', 'curDay.close_price as curDayClose', 't', NULL, '100', NULL, 't'),
('67', '5', 'AfterFiveDayClose', 'AfterFiveDayClose', 'afterFiveDay.close_price as afterFiveDayClose', 'Number', '35', 'afterFiveDay.close_price as afterFiveDayClose', 't', NULL, '100', NULL, 't'),
('68', '5', 'CurrentDayBar', 'CurrentDayBar', '(curDay.close_price-curDay.open_price)*100/NULLIF(curDay.open_price,0) as todaysBar', 'Number', '40', '(curDay.close_price-curDay.open_price)*100/NULLIF(curDay.open_price,0) as todaysBar', 't', NULL, '100', NULL, 't'),
('69', '5', 'VolumeRatio', 'VolumeRatio', 'curDay.volume/NULLIF(prevDay.volume,0) as VolumeRatio', 'Number', '41', 'curDay.volume/NULLIF(prevDay.volume,0)', 't', NULL, '100', NULL, 't'),
('70', '5', 'FiveDayGain', 'FiveDayGain', '(afterFiveDay.close_price-curDay.close_price)*100/NULLIF(curDay.close_price,0) as gainInFiveDay', 'Number', '45', '(afterFiveDay.close_price-curDay.close_price)*100/NULLIF(curDay.close_price,0) as gainInFiveDay', 't', NULL, '100', NULL, 't'),
('71', '5', 'PrevDayStochasticDValue', 'PrevDayStochasticDValue', 'abs(prevDay.stochastic_value) as prevDayStochasticDValue', 'Number', '50', 'abs(prevDay.stochastic_value) as prevDayStochasticDValue', 't', NULL, '100', NULL, 't'),
('72', '5', 'PrevDayStochasticKValue', 'PrevDayStochasticKValue', 'prevDay.autoscan_study_77 as prevDayStochasticKValue', 'Number', '55', 'prevDay.autoscan_study_77 as prevDayStochasticKValue', 't', NULL, '100', NULL, 't'),
('73', '5', 'CurrentDayStochasticDValue', 'CurrentDayStochasticDValue', 'abs(curDay.stochastic_value) as curDayStochasticDValue', 'Number', '60', 'abs(curDay.stochastic_value) as curDayStochasticDValue', 't', NULL, '100', NULL, 't'),
('74', '5', 'CurrentDayStochasticKValue', 'CurrentDayStochasticKValue', 'curDay.autoscan_study_77 as curDayStochasticKValue', 'Number', '65', 'curDay.autoscan_study_77 as curDayStochasticKValue', 't', NULL, '100', NULL, 't'),
('75', '5', 'StochasticKDiff', 'StochasticKDiff', 'curDay.autoscan_study_77-prevDay.autoscan_study_77 as stochasticDiff', 'Number', '70', 'curDay.autoscan_study_77-prevDay.autoscan_study_77 as stochasticDiff', 't', NULL, '100', NULL, 't'),
('76', '5', 'PrevDayMA15VsClosePrice', 'PrevDayMA15VsClosePrice', 'prevDay.close_price-prevDay.autoscan_study_85 as prevDayMA15VsClosePrice', 'Number', '75', 'prevDay.close_price-prevDay.autoscan_study_85 as prevDayMA15VsClosePrice', 't', NULL, '100', NULL, 't'),
('77', '5', 'CurrentMA15VsClosePrice', 'curDayMA15VsClosePrice', 'curDay.close_price-curDay.autoscan_study_85 as curDayMA15VsClosePrice', 'Number', '80', 'curDay.close_price-curDay.autoscan_study_85 as curDayMA15VsClosePrice', 't', NULL, '100', NULL, 't'),
('78', '5', 'PrevDayEMA15VsClosePrice', 'PrevDayEMA15VsClosePrice', 'prevDay.close_price-prevDay.autoscan_study_88 as prevDayEMA15VsClosePrice', 'Number', '85', 'prevDay.close_price-prevDay.autoscan_study_88 as prevDayEMA15VsClosePrice', 't', NULL, '100', NULL, 't'),
('79', '5', 'CurentDayEMA15VsClosePrice', 'CurrentDayEMA15VsClosePrice', 'curDay.close_price-curDay.autoscan_study_88 as curDayEMA15VsClosePrice', 'Number', '90', 'curDay.close_price-curDay.autoscan_study_88 as curDayEMA15VsClosePrice', 't', NULL, '100', NULL, 't'),
('80', '5', 'PrevDayMA15', 'PrevDayMA15', 'prevDay.autoscan_study_85 as prevDayMA15', 'Number', '95', 'prevDay.autoscan_study_85 as prevDayMA15', 't', NULL, '100', NULL, 't'),
('81', '5', 'CurentDayMA15', 'CurentDayMA15', 'curDay.autoscan_study_85 as curDayMA15', 'Number', '100', 'curDay.autoscan_study_85 as curDayMA15', 't', NULL, '100', NULL, 't'),
('82', '5', 'MA15Diff', 'MA15Diff', 'curDay.autoscan_study_85-prevDay.autoscan_study_85 as ma15Diff', 'Number', '105', 'curDay.autoscan_study_85-prevDay.autoscan_study_85 as ma15Diff', 't', NULL, '100', NULL, 't'),
('83', '5', 'PrevDayMA30', 'PrevDayMA30', 'prevDay.autoscan_study_73 as prevDayMA30', 'Number', '110', 'prevDay.autoscan_study_73 as prevDayMA30', 't', NULL, '100', NULL, 't'),
('84', '5', 'CurrentDayMA30', 'CurrentDayMA30', 'curDay.autoscan_study_73 as curDayMA30', 'Number', '115', 'curDay.autoscan_study_73 as curDayMA30', 't', NULL, '100', NULL, 't'),
('85', '5', 'MA30Diff', 'MA30Diff', 'curDay.autoscan_study_73-prevDay.autoscan_study_73 as ma30Diff', 'Number', '120', 'curDay.autoscan_study_73-prevDay.autoscan_study_73 as ma30Diff', 't', NULL, '100', NULL, 't'),
('86', '5', 'PrevDayMA50', 'PrevDayMA50', 'prevDay.autoscan_study_78 as prevDayMA50', 'Number', '125', 'prevDay.autoscan_study_78 as prevDayMA50', 't', NULL, '100', NULL, 't'),
('87', '5', 'CurrentDayMA50', 'CurrentDayMA50', 'curDay.autoscan_study_78 as curDayMA50', 'Number', '130', 'curDay.autoscan_study_78 as curDayMA50', 't', NULL, '100', NULL, 't'),
('88', '5', 'MA50Diff', 'MA50Diff', 'curDay.autoscan_study_78-prevDay.autoscan_study_78 as ma50Diff', 'Number', '135', 'curDay.autoscan_study_78-prevDay.autoscan_study_78 as ma50Diff', 't', NULL, '100', NULL, 't'),
('89', '5', 'PrevDayMA100', 'PrevDayMA100', 'prevDay.autoscan_study_79 as prevDayMA100', 'Number', '140', 'prevDay.autoscan_study_79 as prevDayMA100', 't', NULL, '100', NULL, 't'),
('90', '5', 'CurrentDayMA100', 'CurrentDayMA100', 'curDay.autoscan_study_79 as curDayMA100', 'Number', '145', 'curDay.autoscan_study_79 as curDayMA100', 't', NULL, '100', NULL, 't'),
('91', '5', 'MA100Diff', 'MA100Diff', 'curDay.autoscan_study_79-prevDay.autoscan_study_79 as ma100Diff', 'Number', '150', 'curDay.autoscan_study_79-prevDay.autoscan_study_79 as ma100Diff', 't', NULL, '100', NULL, 't'),
('92', '5', 'PrevDayMA200', 'PrevDayMA200', 'prevDay.autoscan_study_80 as prevDayMA200', 'Number', '155', 'prevDay.autoscan_study_80 as prevDayMA200', 't', NULL, '100', NULL, 't'),
('93', '5', 'CurrentDayMA200', 'CurrentDayMA200', 'curDay.autoscan_study_80 as curDayMA200', 'Number', '160', 'curDay.autoscan_study_80 as curDayMA200', 't', NULL, '100', NULL, 't'),
('94', '5', 'MA200Diff', 'MA200Diff', 'curDay.autoscan_study_80-prevDay.autoscan_study_80 as ma200Diff', 'Number', '165', 'curDay.autoscan_study_80-prevDay.autoscan_study_80 as ma200Diff', 't', NULL, '100', NULL, 't'),
('95', '5', 'PrevDayEMA15', 'PrevDayEMA15', 'prevDay.autoscan_study_88 as prevDayEMA15', 'Number', '170', 'prevDay.autoscan_study_88 as prevDayEMA15', 't', NULL, '100', NULL, 't'),
('96', '5', 'CurrentDayEMA15', 'CurrentDayEMA15', 'curDay.autoscan_study_88 as curDayEMA15', 'Number', '175', 'curDay.autoscan_study_88 as curDayEMA15', 't', NULL, '100', NULL, 't'),
('97', '5', 'EMA15Diff', 'EMA15Diff', 'curDay.autoscan_study_88-prevDay.autoscan_study_88 as ema15Diff', 'Number', '180', 'curDay.autoscan_study_88-prevDay.autoscan_study_88 as ema15Diff', 't', NULL, '100', NULL, 't'),
('98', '5', 'PrevDayEMA30', 'PrevDayEMA30', 'prevDay.autoscan_study_72 as prevDayEMA30', 'Number', '185', 'prevDay.autoscan_study_72 as prevDayEMA30', 't', NULL, '100', NULL, 't'),
('99', '5', 'CurrentDayEMA30', 'CurrentDayEMA30', 'curDay.autoscan_study_72 as curDayEMA30', 'Number', '190', 'curDay.autoscan_study_72 as curDayEMA30', 't', NULL, '100', NULL, 't'),
('100', '5', 'EMA30Diff', 'EMA30Diff', 'curDay.autoscan_study_72-prevDay.autoscan_study_72 as ema30Diff', 'Number', '195', 'curDay.autoscan_study_72-prevDay.autoscan_study_72 as ema30Diff', 't', NULL, '100', NULL, 't'),
('101', '5', 'PrevDayEMA50', 'PrevDayEMA50', 'prevDay.autoscan_study_89 as prevDayEMA50', 'Number', '200', 'prevDay.autoscan_study_89 as prevDayEMA50', 't', NULL, '100', NULL, 't'),
('102', '5', 'CurrentDayEMA50', 'CurrentDayEMA50', 'curDay.autoscan_study_89 as curDayEMA50', 'Number', '205', 'curDay.autoscan_study_89 as curDayEMA50', 't', NULL, '100', NULL, 't'),
('103', '5', 'EMA50Diff', 'EMA50Diff', 'curDay.autoscan_study_89-prevDay.autoscan_study_89 as ema50Diff', 'Number', '210', 'curDay.autoscan_study_89-prevDay.autoscan_study_89 as ema50Diff', 't', NULL, '100', NULL, 't'),
('104', '5', 'PrevDayEMA100', 'PrevDayEMA100', 'prevDay.autoscan_study_90 as prevDayEMA100', 'Number', '215', 'prevDay.autoscan_study_90 as prevDayEMA100', 't', NULL, '100', NULL, 't'),
('105', '5', 'CurrentDayEMA100', 'CurrentDayEMA100', 'curDay.autoscan_study_90 as curDayEMA100', 'Number', '220', 'curDay.autoscan_study_90 as curDayEMA100', 't', NULL, '100', NULL, 't'),
('106', '5', 'EMA100Diff', 'EMA100Diff', 'curDay.autoscan_study_90-prevDay.autoscan_study_90 as ema100Diff', 'Number', '225', 'curDay.autoscan_study_90-prevDay.autoscan_study_90 as ema100Diff', 't', NULL, '100', NULL, 't'),
('107', '5', 'PrevDayEMA200', 'PrevDayEMA200', 'prevDay.autoscan_study_91 as prevDayEMA200', 'Number', '230', 'prevDay.autoscan_study_91 as prevDayEMA200', 't', NULL, '230', NULL, 't'),
('108', '5', 'CurrentDayEMA200', 'CurrentDayEMA200', 'curDay.autoscan_study_91 as curDayEMA200', 'Number', '235', 'curDay.autoscan_study_91 as curDayEMA200', 't', NULL, '100', NULL, 't'),
('109', '5', 'EMA200Diff', 'EMA200Diff', 'curDay.autoscan_study_91-prevDay.autoscan_study_91 as ema200Diff', 'Number', '240', 'curDay.autoscan_study_91-prevDay.autoscan_study_91 as ema200Diff', 't', NULL, '100', NULL, 't'),
('110', '5', 'PrevDayMACD12269', 'PrevDayMACD12269', 'prevDay.autoscan_study_4 as prevDayMACD12269', 'Number', '245', 'prevDay.autoscan_study_4 as prevDayMACD12269', 't', NULL, '100', NULL, 't'),
('111', '5', 'CurrentDayMACD12269', 'CurrentDayMACD12269', 'curDay.autoscan_study_4 as curDayMACD12269', 'Number', '250', 'curDay.autoscan_study_4 as curDayMACD12269', 't', NULL, '100', NULL, 't'),
('112', '5', 'MACD12269Diff', 'MACD12269Diff', 'curDay.autoscan_study_4-prevDay.autoscan_study_4 as macd12269Diff', 'Number', '255', 'curDay.autoscan_study_4-prevDay.autoscan_study_4 as macd12269Diff', 't', NULL, '100', NULL, 't'),
('113', '5', 'PrevDayMACD8179', 'PrevDayMACD8179', 'prevDay.autoscan_study_74 as prevDayMACD8179', 'Number', '260', 'prevDay.autoscan_study_74 as prevDayMACD8179', 't', NULL, '100', NULL, 't'),
('114', '5', 'CurrentDayMACD8179', 'CurrentDayMACD8179', 'curDay.autoscan_study_74 as curDayMACD8179', 'Number', '265', 'curDay.autoscan_study_74 as curDayMACD8179', 't', NULL, '100', NULL, 't'),
('115', '5', 'MACD8179Diff', 'MACD8179Diff', 'curDay.autoscan_study_74-prevDay.autoscan_study_74 as macd8179Diff', 'Number', '270', 'curDay.autoscan_study_74-prevDay.autoscan_study_74 as macd8179Diff', 't', NULL, '100', NULL, 't'),
('116', '5', 'PrevDayMACD6024020', 'PrevDayMACD6024020', 'prevDay.autoscan_study_70 as prevDayMACD6024020', 'Number', '280', 'prevDay.autoscan_study_70 as prevDayMACD6024020', 't', NULL, '100', NULL, 't'),
('117', '5', 'CurrentDayMACD6024020', 'CurrentDayMACD6024020', 'curDay.autoscan_study_70 as curDayMACD6024020', 'Number', '285', 'curDay.autoscan_study_70 as curDayMACD6024020', 't', NULL, '100', NULL, 't'),
('118', '5', 'MACD6024020Diff', 'MACD6024020Diff', 'curDay.autoscan_study_70-prevDay.autoscan_study_70 as macd6024020Diff', 'Number', '290', 'curDay.autoscan_study_70-prevDay.autoscan_study_70 as macd6024020Diff', 't', NULL, '100', NULL, 't'),
('119', '5', 'PrevDayCCI', 'PrevDayCCI', 'prevDay.autoscan_study_71 as prevDayCCI', 'Number', '295', 'prevDay.autoscan_study_71 as prevDayCCI', 't', NULL, '100', NULL, 't'),
('120', '5', 'CurrentDayCCI', 'CurrentDayCCI', 'curDay.autoscan_study_71 as curDayCCI', 'Number', '300', 'curDay.autoscan_study_71 as curDayCCI', 't', NULL, '100', NULL, 't'),
('121', '5', 'CCIDiff', 'CCIDiff', 'curDay.autoscan_study_71-prevDay.autoscan_study_71 as cciDiff', 'Number', '305', 'curDay.autoscan_study_71-prevDay.autoscan_study_71 as cciDiff', 't', NULL, '100', NULL, 't'),
('122', '5', 'PrevDayMomentum', 'PrevDayMomentum', 'prevDay.autoscan_study_75 as prevDayMomentum', 'Number', '310', 'prevDay.autoscan_study_75 as prevDayMomentum', 't', NULL, '100', NULL, 't'),
('123', '5', 'CurrentDayMomentum', 'CurrentDayMomentum', 'curDay.autoscan_study_75 as curDayMomentum', 'Number', '315', 'curDay.autoscan_study_75 as curDayMomentum', 't', NULL, '100', NULL, 't'),
('124', '5', 'momentumDiff', 'momentumDiff', 'curDay.autoscan_study_75-prevDay.autoscan_study_75 as momentumDiff', 'Number', '320', 'curDay.autoscan_study_75-prevDay.autoscan_study_75 as momentumDiff', 't', NULL, '100', NULL, 't'),
('125', '5', 'PrevDayRSI', 'PrevDayRSI', 'prevDay.autoscan_study_76 as prevDayRSI', 'Number', '325', 'prevDay.autoscan_study_76 as prevDayRSI', 't', NULL, '100', NULL, 't'),
('130', '5', 'CurrentDayRSI', 'CurrentDayRSI', 'curDay.autoscan_study_76 as curDayRSI', 'Number', '330', 'curDay.autoscan_study_76 as curDayRSI', 't', NULL, '100', NULL, 't'),
('131', '5', 'RsiDiff', 'RsiDiff', 'curDay.autoscan_study_76-prevDay.autoscan_study_76 as rsiDiff', 'Number', '335', 'curDay.autoscan_study_76-prevDay.autoscan_study_76 as rsiDiff', 't', NULL, '100', NULL, 't'),
('132', '5', 'PrevDayTTF', 'PrevDayTTF', 'prevDay.autoscan_study_84 as prevDayTTF', 'Number', '340', 'prevDay.autoscan_study_84 as prevDayTTF', 't', NULL, '100', NULL, 't'),
('133', '5', 'CurrentDayTTF', 'CurrentDayTTF', 'curDay.autoscan_study_84 as curDayTTF', 'Number', '345', 'curDay.autoscan_study_84 as curDayTTF', 't', NULL, '100', NULL, 't'),
('134', '5', 'ttfDiff', 'ttfDiff', 'curDay.autoscan_study_84-prevDay.autoscan_study_84 as ttfDiff', 'Number', '350', 'curDay.autoscan_study_84-prevDay.autoscan_study_84 as ttfDiff', 't', NULL, '100', NULL, 't');

INSERT INTO db_versions VALUES('0025', now(), 'Keshav', 'New jqGrid for advanced technical analysis','Schema' );