-- Candlestick scans
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES ( 5,3,'CDL2CROWS','Two Crows','Candlestick Two Crows');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES ( 6,3,'CDL3BLACKCROWS','Three Black Crows','Candlestick Three Black Crows');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES ( 7,3,'CDL3INSIDE','Three Inside Up/Down','Candlestick Three Inside Up/Down');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES ( 8,3,'CDL3LINESTRIKE','Three-Line Strike','Candlestick Three-Line Strike');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES ( 9,3,'CDL3OUTSIDE','Three Outside Up/Down','Candlestick Three Outside Up/Down');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (10,3,'CDL3STARSINSOUTH','Three Stars In The South','Candlestick Three Stars In The South');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (11,3,'CDL3WHITESOLDIERS','Three Advancing White Soldiers','Candlestick Three Advancing White Soldiers');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (12,3,'CDLABANDONEDBABY','Abandoned Baby','Candlestick Abandoned Baby');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (13,3,'CDLADVANCEBLOCK','Advance Block','Candlestick Advance Block');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (14,3,'CDLBELTHOLD','Belt-hold','Candlestick Belt-hold');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (15,3,'CDLBREAKAWAY','Breakaway','Candlestick Breakaway');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (16,3,'CDLCLOSINGMARUBOZU','Closing Marubozu','Candlestick Closing Marubozu');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (17,3,'CDLCONCEALBABYSWALL','Concealing Baby Swallow','Candlestick Concealing Baby Swallow');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (18,3,'CDLCOUNTERATTACK','Counterattack','Candlestick Counterattack');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (19,3,'CDLDARKCLOUDCOVER','Dark Cloud Cover','Candlestick Dark Cloud Cover');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (20,3,'CDLDOJI','Doji','Candlestick Doji');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (21,3,'CDLDOJISTAR','Doji Star','Candlestick Doji Star');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (22,3,'CDLDRAGONFLYDOJI','Dragonfly Doji','Candlestick Dragonfly Doji');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (23,3,'CDLENGULFING','Engulfing Pattern','Candlestick Engulfing Pattern');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (24,3,'CDLEVENINGDOJISTAR','Evening Doji Star','Candlestick Evening Doji Star');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (25,3,'CDLEVENINGSTAR','Evening Star','Candlestick Evening Star');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (26,3,'CDLGAPSIDESIDEWHITE','Up/Down-gap side-by-side white lines','Candlestick Up/Down-gap side-by-side white lines');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (27,3,'CDLGRAVESTONEDOJI','Gravestone Doji','Candlestick Gravestone Doji');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (28,3,'CDLHAMMER','Hammer','Candlestick Hammer');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (29,3,'CDLHANGINGMAN','Hanging Man','Candlestick Hanging Man');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (30,3,'CDLHARAMI','Harami Pattern','Candlestick Harami Pattern');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (31,3,'CDLHARAMICROSS','Harami Cross Pattern','Candlestick Harami Cross Pattern');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (32,3,'CDLHIGHWAVE','High-Wave Candle','Candlestick High-Wave Candle');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (33,3,'CDLHIKKAKE','Hikkake Pattern','Candlestick Hikkake Pattern');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (35,3,'CDLHIKKAKEMOD','Modified Hikkake Pattern','Candlestick Modified Hikkake Pattern');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (36,3,'CDLHOMINGPIGEON','Homing Pigeon','Candlestick Homing Pigeon');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (37,3,'CDLIDENTICAL3CROWS','Identical Three Crows','Candlestick Identical Three Crows');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (38,3,'CDLINNECK','In-Neck Pattern','Candlestick In-Neck Pattern');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (39,3,'CDLINVERTEDHAMMER','Inverted Hammer','Candlestick Inverted Hammer');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (40,3,'CDLKICKING','Kicking','Candlestick Kicking');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (41,3,'CDLKICKINGBYLENGTH','Kicking - bull/bear determined by the longer marubozu','Candlestick Kicking - bull/bear determined by the longer marubozu');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (42,3,'CDLLADDERBOTTOM','Ladder Bottom','Candlestick Ladder Bottom');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (43,3,'CDLLONGLEGGEDDOJI','Long Legged Doji','Candlestick Long Legged Doji');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (45,3,'CDLLONGLINE','Long Line Candle','Candlestick Long Line Candle');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (46,3,'CDLMARUBOZU','Marubozu','Candlestick Marubozu');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (47,3,'CDLMATCHINGLOW','Matching Low','Candlestick Matching Low');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (48,3,'CDLMATHOLD','Mat Hold','Candlestick Mat Hold');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (49,3,'CDLMORNINGDOJISTAR','Morning Doji Star','Candlestick Morning Doji Star');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (50,3,'CDLMORNINGSTAR','Morning Star','Candlestick Morning Star');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (51,3,'CDLONNECK','On-Neck Pattern','Candlestick On-Neck Pattern');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (52,3,'CDLPIERCING','Piercing Pattern','Candlestick Piercing Pattern');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (53,3,'CDLRICKSHAWMAN','Rickshaw Man','Candlestick Rickshaw Man');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (55,3,'CDLRISEFALL3METHODS','Rising/Falling Three Methods','Candlestick Rising/Falling Three Methods');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (56,3,'CDLSEPARATINGLINES','Separating Lines','Candlestick Separating Lines');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (57,3,'CDLSHOOTINGSTAR','Shooting Star','Candlestick Shooting Star');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (58,3,'CDLSHORTLINE','Short Line Candle','Candlestick Short Line Candle');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (59,3,'CDLSPINNINGTOP','Spinning Top','Candlestick Spinning Top');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (60,3,'CDLSTALLEDPATTERN','Stalled Pattern','Candlestick Stalled Pattern');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (61,3,'CDLSTICKSANDWICH','Stick Sandwich','Candlestick Stick Sandwich');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (62,3,'CDLTAKURI','Takuri (Dragonfly Doji with very long lower shadow)','Candlestick Takuri (Dragonfly Doji with very long lower shadow)');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (63,3,'CDLTASUKIGAP','Tasuki Gap','Candlestick Tasuki Gap');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (65,3,'CDLTHRUSTING','Thrusting Pattern','Candlestick Thrusting Pattern');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (66,3,'CDLTRISTAR','Tristar Pattern','Candlestick Tristar Pattern');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (67,3,'CDLUNIQUE3RIVER','Unique 3 River','Candlestick Unique 3 River');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (68,3,'CDLUPSIDEGAP2CROWS','Upside Gap Two Crows','Candlestick Upside Gap Two Crows');
INSERT INTO autoscan_study_library (id, study_type, shortname, study_name, description) VALUES (69,3,'CDLXSIDEGAP3METHODS','Upside/Downside Gap Three Methods','Candlestick Upside/Downside Gap Three Methods');
INSERT INTO db_versions VALUES('0008', now(), 'Keshav', 'Candlestick Autoscan entries','Schema' );